baseURL = "http://thezachsmith.com"
languageCode = "en-us"
title = "TheZachSmith Forge"
theme = "nix"

[params]
	Name = "TheZachSmith"
	HeaderUsername = "theZachSmith"
	HeaderHostname = "forge"
	About = "Welcome to my digital forge! I'm a Computer Engineer by trade but enjoy making all kinds of things. I plan to post blogs here about my creations."
	ProfilePicture = "/img/thezachsmithcom.png"
	nocomments = true
	blogOnIndex = true
	GithubID = "Zsmith32"
	LinkedInID = "zachsmithforge"
	Email = "smith.zach.p@gmail.com"
	TwitterID = "The_Zach_Smith"
	RSSURL = "/index.xml"

[menu]
	[[menu.header]]
		name = "blog"
		weight = 0
		url = "/posts"
